#!/usr/bin/env python3
"""Build memory indexes from episode + playbook source files.

Regenerates two deterministic indexes used by scripts/memory_retrieve.py:
    memory/episodes/INDEX.yaml   ← from memory/episodes/*.yaml
    memory/playbook/INDEX.yaml   ← from memory/playbook/*.md (ENTRY markers)

Like generate_frontend_manifest.py, output is byte-stable for identical inputs
so CI can detect drift with --check. The index is keyword/tag based — no vector
store — keeping memory auditable and dependency-free (see Decision D008).

Playbook entry marker convention (see memory/playbook/PLAYBOOK_ENTRY_TEMPLATE.md):
    <!-- ENTRY id=PB-research-001 skill=research tags=web-search,rate-limit -->
    ## entry title
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
EPISODES_DIR = ROOT / "memory" / "episodes"
PLAYBOOK_DIR = ROOT / "memory" / "playbook"
EPISODES_INDEX = EPISODES_DIR / "INDEX.yaml"
PLAYBOOK_INDEX = PLAYBOOK_DIR / "INDEX.yaml"

GENERATED_HEADER = (
    "# Auto-generated by scripts/build_memory_index.py — do not edit by hand.\n"
    "# Re-run after adding/editing episodes or playbook entries.\n"
)

ENTRY_RE = re.compile(
    r"<!--\s*ENTRY\s+id=(?P<id>[\w.\-]+)\s+skill=(?P<skill>\w+)\s+tags=(?P<tags>[\w,.\-]*)\s*-->"
)


def _is_source(path: Path) -> bool:
    name = path.name
    return path.is_file() and "TEMPLATE" not in name and name != "INDEX.yaml"


def load_yaml(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    return data if isinstance(data, dict) else {}


def _split_tags(raw: str | list | None) -> list[str]:
    if isinstance(raw, list):
        return [str(t).strip() for t in raw if str(t).strip()]
    if isinstance(raw, str):
        return [t.strip() for t in raw.split(",") if t.strip()]
    return []


def collect_episodes(root: Path) -> list[dict[str, Any]]:
    items = []
    for p in sorted((root / "memory" / "episodes").glob("*.yaml")):
        if not _is_source(p):
            continue
        doc = load_yaml(p)
        if not doc.get("episode_id"):
            continue
        items.append({
            "id": str(doc.get("episode_id", "")),
            "path": p.relative_to(root).as_posix(),
            "skill_type": str(doc.get("skill_type", "")),
            "outcome": str(doc.get("outcome", "")),
            "tags": _split_tags(doc.get("tags")),
            "goal": str(doc.get("goal", "")),
        })
    items.sort(key=lambda d: d["id"])
    return items


def collect_playbook(root: Path) -> list[dict[str, Any]]:
    items = []
    for p in sorted((root / "memory" / "playbook").glob("*.md")):
        if not _is_source(p):
            continue
        lines = p.read_text(encoding="utf-8").splitlines()
        rel = p.relative_to(root).as_posix()
        i = 0
        while i < len(lines):
            m = ENTRY_RE.search(lines[i])
            if not m:
                i += 1
                continue
            # title = next non-empty line, strip a leading "## "
            title = ""
            j = i + 1
            while j < len(lines):
                stripped = lines[j].strip()
                if stripped:
                    title = re.sub(r"^#+\s*", "", stripped)
                    break
                j += 1
            items.append({
                "id": m.group("id"),
                "path": rel,
                "skill_type": m.group("skill"),
                "tags": _split_tags(m.group("tags")),
                "title": title,
            })
            i += 1
    items.sort(key=lambda d: d["id"])
    return items


def dump_index(header_key: str, items: list[dict[str, Any]]) -> str:
    payload = {header_key: items}
    body = yaml.safe_dump(payload, sort_keys=True, allow_unicode=True, default_flow_style=False)
    return GENERATED_HEADER + body


def _write_or_check(path: Path, rendered: str, check: bool) -> int:
    if check:
        existing = path.read_text(encoding="utf-8") if path.exists() else ""
        if existing != rendered:
            print(
                f"DRIFT: {path.relative_to(ROOT)} is out of date. "
                "Re-run scripts/build_memory_index.py.",
                file=sys.stderr,
            )
            return 1
        return 0
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(rendered, encoding="utf-8")
    return 0


def main(argv: list[str] | None = None) -> int:
    args = argv if argv is not None else sys.argv[1:]
    check = "--check" in args

    episodes = collect_episodes(ROOT)
    playbook = collect_playbook(ROOT)
    ep_doc = dump_index("episodes", episodes)
    pb_doc = dump_index("entries", playbook)

    rc = 0
    rc |= _write_or_check(EPISODES_INDEX, ep_doc, check)
    rc |= _write_or_check(PLAYBOOK_INDEX, pb_doc, check)

    if check:
        if rc == 0:
            print("OK: memory indexes are up to date.")
        return rc
    print(f"Built memory indexes ({len(episodes)} episodes, {len(playbook)} playbook entries).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
