#!/usr/bin/env python3
"""Generate frontend/manifest.js from repository files."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FRONTEND_DIR = ROOT / "frontend"
OUTPUT = FRONTEND_DIR / "manifest.js"


def to_frontend_relative(path: Path) -> str:
    return "../" + path.relative_to(ROOT).as_posix()


def list_files(pattern: str) -> list[str]:
    return sorted(
        to_frontend_relative(p)
        for p in ROOT.glob(pattern)
        if p.is_file()
    )


def as_js_array(name: str, values: list[str]) -> str:
    items = ",\n".join(f"  '{v}'" for v in values)
    if items:
        return f"export const {name} = [\n{items}\n];\n"
    return f"export const {name} = [];\n"


def main() -> None:
    task_files = list_files("tasks/20*.yaml")
    log_files = list_files("logs/runs/*.yaml")
    decision_files = list_files("memory/active_projects/agent-harness/decisions/*.yaml")

    content = "// Auto-generated by scripts/generate_frontend_manifest.py\n"
    content += "// Do not edit this file manually.\n\n"
    content += as_js_array("TASK_FILES", task_files)
    content += "\n"
    content += as_js_array("LOG_FILES", log_files)
    content += "\n"
    content += as_js_array("DECISION_FILES", decision_files)

    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
